#!/bin/bash
# =============================================================================
# Reinder — setup.sh
# Configura el entorno de desarrollo completo de forma interactiva.
# Uso: bash setup.sh
# =============================================================================

set -e

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/apps/web/.env.local"

echo ""
echo -e "${BOLD}${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${CYAN}║        Reinder — Dev Setup               ║${NC}"
echo -e "${BOLD}${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""

# ─── Step 0: Check prerequisites ─────────────────────────────────────────────

echo -e "${CYAN}[1/4] Verificando prerequisitos...${NC}"

if ! command -v node &>/dev/null; then
  echo -e "${RED}✗ Node.js no encontrado. Instala con: brew install node${NC}"
  exit 1
fi

if ! command -v pnpm &>/dev/null; then
  echo -e "${YELLOW}⚠ pnpm no encontrado. Instalando...${NC}"
  npm install -g pnpm
fi

echo -e "${GREEN}✓ Node $(node --version), pnpm $(pnpm --version)${NC}"

# ─── Step 1: Collect Supabase credentials ─────────────────────────────────────

echo ""
echo -e "${CYAN}[2/4] Configurando variables de entorno...${NC}"
echo ""
echo -e "${YELLOW}Necesitas tus credenciales de Supabase. Ábrelas en:${NC}"
echo -e "${BOLD}  https://supabase.com/dashboard/project/_/settings/api${NC}"
echo ""

# If .env.local exists and has values, skip
if [ -f "$ENV_FILE" ] && grep -q "NEXT_PUBLIC_SUPABASE_URL=https://" "$ENV_FILE" 2>/dev/null; then
  echo -e "${GREEN}✓ .env.local ya configurado. Saltando.${NC}"
else
  # Collect values interactively
  echo -e "${BOLD}Project URL${NC} (ej: https://xxxx.supabase.co):"
  read -r SUPABASE_URL
  
  echo ""
  echo -e "${BOLD}Anon Key${NC} (empieza por eyJ...):"
  read -r SUPABASE_ANON_KEY
  
  echo ""
  echo -e "${BOLD}Database URL${NC} — Connection pooling → Transaction mode (puerto 6543):"
  echo -e "${YELLOW}  Ej: postgresql://postgres.xxxx:[PASSWORD]@aws-0-eu-west-3.pooler.supabase.com:6543/postgres${NC}"
  read -r DATABASE_URL

  # Write .env.local
  cat > "$ENV_FILE" << EOF
# Reinder — apps/web — Local Environment
# Generated by setup.sh on $(date)

NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
DATABASE_URL=${DATABASE_URL}
NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF

  echo ""
  echo -e "${GREEN}✓ .env.local creado en apps/web/.env.local${NC}"
fi

# ─── Step 2: Install dependencies ─────────────────────────────────────────────

echo ""
echo -e "${CYAN}[3/4] Instalando dependencias...${NC}"
pnpm install --frozen-lockfile 2>&1 | tail -5
echo -e "${GREEN}✓ Dependencias instaladas${NC}"

# ─── Step 3: Run database migrations ──────────────────────────────────────────

echo ""
echo -e "${CYAN}[4/4] Aplicando migraciones de base de datos...${NC}"

# Load env for migration
set -a
source "$ENV_FILE"
set +a

if pnpm db:migrate 2>&1 | tail -10; then
  echo -e "${GREEN}✓ Migraciones aplicadas correctamente${NC}"
else
  echo -e "${RED}✗ Error aplicando migraciones. Verifica tu DATABASE_URL.${NC}"
  echo -e "${YELLOW}  Ejecuta manualmente: pnpm db:migrate${NC}"
fi

# ─── Done ─────────────────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║  ✅ Setup completado                      ║${NC}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Arranca el servidor con: ${BOLD}pnpm dev${NC}"
echo -e "  Accede en:               ${BOLD}http://localhost:3000${NC}"
echo ""
